### ISSUE TITLE
Error during parsing rate_limit

### ISSUE THREAD

**Issue by zxiest** [RussellLuo/caddy-ext#13]
Hello there,

Any idea why I'm getting the error below?

Error during parsing: parsing caddyfile tokens for 'rate_limit': /etc/caddy/Caddyfile:25 - 
Error during parsing: Wrong argument count or unexpected line ending after '{http.request.uri.query.id}'

```
localhost:8080 {
    route /foo {
        rate_limit {query.id} 2r/m

        respond 200
    }
}
```

This is my Dockerfile

```
FROM caddy:2.6.2-builder-alpine as builder

RUN xcaddy build \
    --with github.com/RussellLuo/caddy-ext/ratelimit

FROM caddy:2.6.2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

and this is my docker-compose.yml

```
version: "3.7"

services:
  caddy:
    logging:
      options:
        max-size: "500m"
        max-file: "5"

    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
volumes:
  caddy_data:
  caddy_config:

```
